title: maDMP Evaluation
authors:
  - raffaelfoidl:
    name: Raffael Foidl
    email: raffael.foidl@student.tuwien.ac.at
  - bruggerl:
    name: Lea Salome Brugger
    email: lea.brugger@student.tuwien.ac.at
description: >
  A project to facilitate the automatic assessment of the quality of machine-actionable data management. Especially
  conceived SPARQL queries to be executed over a DCSO serialization - in this instance, JSON-LD - allow for making
  solid assumptions about the informational value of a maDMP.

permalink: /:title.html

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - github.md

footer_icons:
  - username: raffaelfoidl/maDMP-evaluation/
    url: https://github.com/raffaelfoidl/maDMP-evaluation
    icon: icon-github.svg

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
